package org.model;

public class MonstersDescriptions {
    public static String Geralt = "“Evil is Evil. Lesser, greater, middling… Makes no difference. The degree is arbitary. The definition’s blurred. If I’m to choose between one evil and another… I’d rather not choose at all.”";
    public static String cerberus = "Those banished from heavens to guard the HELL";
    public static String graphicLord = "The one and only who knows about the dark secrets of javaFX";
    public static String SPN = "ONE may know many secrets but he is the ONE who know them all .";
    public static String TheMaster = "He who knows all the secrets.\nHe who taught us all we know.";
    public static String commandKnight = "All Warrior-Type monsters you control gain 400 ATK. If you control another monster, monsters your opponent controls cannot target this card for an attack.";
    public static String battleOX  = "A monster with tremendous power, it destroys enemies with a swing of its axe.";
    public static String axeRaider = "An axe-wielding monster of tremendous strength and agility.";
    public static String yomiShip = "If this card is destroyed by battle and sent to the GY: Destroy the monster that destroyed this card.";
    public static String hornImp = "A small fiend that dwells in the dark, its single horn makes it a formidable opponent.";
    public static String silverFang = "A snow wolf that's beautiful to the eye, but absolutely vicious in battle.";
    public static String suijin = "During damage calculation in your opponent's turn, if this card is being attacked: You can target the attacking monster; make that target's ATK 0 during damage calculation only (this is a Quick Effect). This effect can only be used once while this card is face-up on the field.";
    public static String fireYarou = "A malevolent creature wrapped in flames that attacks enemies with intense fire.";
    public static String curtainOfTheDarkOnes = "A curtain that a spellcaster made, it is said to raise a dark power.";
    public static String feralImp = "A playful little fiend that lurks in the dark, waiting to attack an unwary enemy.";
    public static String darkMagician ="The ultimate wizard in terms of attack and defense.";
    public static String wattkid = "A creature that electrocutes opponents with bolts of lightning.";
    public static String babyDragon = "Much more than just a child, this dragon is gifted with untapped power.";
    public static String heroOfTheEast= "Feel da strength ah dis sword-swinging samurai from da Far East.";
    public static String battleWarrior = "A warrior that fights with his bare hands!!!";
    public static String crawlingDragon = "This weakened dragon can no longer fly, but is still a deadly force to be reckoned with.";
    public static String flameManipulator = "This Spellcaster attacks enemies with fire-related spells such as \"Sea of Flames\" and \"Wall of Fire\".";
    public static String blueEyesDragon = "This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.";
    public static String crabTurtle = "This monster can only be Ritual Summoned with the Ritual Spell Card, \"Turtle Oath\". You must also offer monsters whose total Level Stars equal 8 or more as a Tribute from the field or your hand.";
    public static String skullGuardian = "This monster can only be Ritual Summoned with the Ritual Spell Card, \"Novox's Prayer\". You must also offer monsters whose total Level Stars equal 7 or more as a Tribute from the field or your hand.";
    public static String slotMachine = "The machine's ability is said to vary according to its slot results.";
    public static String haniwa = "An earthen figure that protects the tomb of an ancient ruler.";
    public static String manEaterBug = "FLIP: Target 1 monster on the field; destroy that target.";
    public static String gateGuardian = "Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by Tributing 1 \"Sanga of the Thunder\", \"Kazejin\", and \"Suijin\".";
    public static String scanner = "Once per turn, you can select 1 of your opponent's monsters that is removed from play. Until the End Phase, this card's name is treated as the selected monster's name, and this card has the same Attribute, Level, ATK, and DEF as the selected monster. If this card is removed from the field while this effect is applied, remove it from play.";
    public static String bitron = "A new species found in electronic space. There's not much information on it.";
    public static String marshmallon = "Cannot be destroyed by battle. After damage calculation, if this card was attacked, and was face-down at the start of the Damage Step: The attacking player takes 1000 damage.";
    public static String beastKing = "You can Normal Summon/Set this card without Tributing, but its original ATK becomes 1900. You can Tribute 3 monsters to Tribute Summon (but not Set) this card. If Summoned this way: Destroy all cards your opponent controls.";
    public static String texChanger = "Once per turn, when your monster is targeted for an attack: You can negate that attack, then Special Summon 1 Cyberse Normal Monster from your hand, Deck, or GY.";
    public static String leotron = "A territorial electronic monster that guards its own domain.";
    public static String theCalculator = "The ATK of this card is the combined Levels of all face-up monsters you control x 300.";
    public static String alexandriteDragon = "Many of the czars' lost jewels can be found in the scales of this priceless dragon. Its creator remains a mystery, along with how they acquired the imperial treasures. But whosoever finds this dragon has hit the jackpot... whether they know it or not.";
    public static String mirageDragon = "Your opponent cannot activate Trap Cards during the Battle Phase.";
    public static String heraldOfTheCreation = "Once per turn: You can discard 1 card, then target 1 Level 7 or higher monster in your Graveyard; add that target to your hand.";
    public static String exploderDragon = "If this card is destroyed by battle and sent to the Graveyard: Destroy the monster that destroyed it. Neither player takes any battle damage from attacks involving this attacking card.";
    public static String warriorDaiGrepher = "The warrior who can manipulate dragons. Nobody knows his mysterious past.";
    public static String darkBlade = "They say he is a dragon-manipulating warrior from the dark world. His attack is tremendous, using his great swords with vicious power.";
    public static String wattailDragon = "\"Capable of indefinite flight. Attacks by wrapping its body with electricity and ramming into opponents.\n" +
            "IMPORTANT: Capturing the \"\"Wattaildragon\"\" is forbidden by the Ancient Rules and is a Level 6 offense, the minimum sentence for which is imprisonment for no less than 2500 heliocycles.\"";
    public static String terraTigerTheEmpoweredWarrior = "When this card is Normal Summoned: You can Special Summon 1 Level 4 or lower Normal Monster from your hand in Defense Position.";
    public static String theTricky = "You can Special Summon this card (from your hand) by discarding 1 card.";
    public static String spiralSerpent = "When huge whirlpools lay cities asunder, it is the hunger of this sea serpent at work. No one has ever escaped its dreaded Spiral Wave to accurately describe the terror they experienced.";
    public static String professorFazli = "The master of snakes(Specially pythons) the man who led us in a great battle to make AP a project based course. ";
}
