package enums;

public enum RecentActionsInGame {
    DECLARED_A_BATTLE,
    SUMMONED_A_MONSTER_WITH_LESS_THAN_1000_ATTACK_POINT,
    SUMMONED_A_MONSTER_WITH_1000_OR_MORE_ATTACK_POINT,
    SPECIAL_SUMMONED,
    IN_OUR_MAIN_PHASE,
    NOTHING
    //TODO: ADD ALL ACTIONS
}
