package Enums;

public enum TrapEffect {
    TRAP_HOLE,
    MIRROR_FORCE,
    MAGIC_CYLINDER,
    MIND_CRUSH,
    TORRENTIAL_TRIBUTE,
    TIME_SEAL,
    NEGATE_ATTACK,
    SOLEMN_WARNING,
    MAGIC_JAMAMER,
    CALL_OF_THE_HAUNTED,
    VANITYS_EMPTINESS,
    WALL_OF_REVEALING_LIGHT,
}
