package model;

public enum MonsterPower {
    NONE,
    COMMAND_KNIGHT,
    YOMI_SHIP,
    SUIJIN,
    MAN_EATER_BUG,
    GATE_GUARDIAN,
    SCANNER,
    CRAB_TURTLE,
    SKULL_GUARDIAN,
    MARSHMALLON,
    BEAST_KING_BARBAROS,
    TEXCHANGER,
    THE_CALCULATOR,
    MIRAGE_DRAGON,
    HERALD_OF_CREATION,
    EXPLODER_DRAGON,
    TERRATIGER_THE_EMPOWERED_WARRIOR,
    THE_TRICKY,

}
