package org.model.enums;

public enum RecentActionsInGame {
    RIVAL_DECLARED_A_BATTLE,
    PLAYER_DECLARED_A_BATTLE,
    RIVAL_SUMMONED_A_MONSTER_WITH_LESS_THAN_1000_ATTACK_POINT,
    RIVAL_SUMMONED_A_MONSTER_WITH_1000_OR_MORE_ATTACK_POINT,
    RIVAL_SPECIAL_SUMMONED,
    PLAYER_SUMMONED,
    IN_OUR_MAIN_PHASE,
    RIVAL_ACTIVATED_A_SPELL_CARD
}
